analysis:
  analysis_raw_dir: /scratch/hadpx/SEA_monitoring/raw_data/analysis/analysis_bucket
  analysis_moose_dir: moose:/opfc/atm/global/prods/
  analysis_dummy_queryfiles_dir: /scratch/hadpx/SEA_monitoring/temp

  mjo:
    analysis_mjo_queryfile: /home/users/prince.xavier/MJO/Monitoring_new/MJO/analysis/mjo_combined.query
    analysis_mjo_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/analysis/
    analysis_mjo_rmm_archive_dir: /project/MJO_GCSS/SEA_monitoring/processed_MJO_data/analysis/rmms/

  eqwaves:
    analysis_eqwaves_query_file: /home/users/prince.xavier/MJO/Monitoring_new/EQWAVES/analysis/eqw_combined.query
    analysis_eqwaves_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/analysis/eqwaves

mogreps:
  mogreps_dummy_queryfiles_dir: /scratch/hadpx/SEA_monitoring/temp
  mogreps_moose_dir: moose:/opfc/atm/mogreps-g/prods/

  mjo:
    mogreps_mjo_queryfile: /home/users/prince.xavier/MJO/Monitoring_new/MJO/mogreps/mjo_combined.query
    mogreps_mjo_raw_dir: /scratch/hadpx/SEA_monitoring/raw_data/mogreps/MJO
    mogreps_mjo_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/mogreps/MJO
    mogreps_mjo_archive_dir: /project/MJO_GCSS/SEA_monitoring/processed_MJO_data/mogreps/rmms_new/
    mogreps_mjo_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_MJO_data/mogreps/plot_ens_new

  eqwaves:
    mogreps_eqwaves_query_file: /home/users/prince.xavier/MJO/Monitoring_new/EQWAVES/mogreps/eqw_combined.query
    mogreps_eqwaves_raw_dir: /scratch/hadpx/SEA_monitoring/raw_data/mogreps/eqwaves
    mogreps_eqwaves_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/mogreps/eqwaves
    mogreps_eqwaves_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_EQW_data/mogreps/plot_ens_new

  cs:
    mogreps_cs_queryfile: /home/users/prince.xavier/MJO/Monitoring_new/COLDSURGE/mogreps/cs_combined.query
    mogreps_cs_raw_dir: /scratch/hadpx/SEA_monitoring/raw_data/mogreps/coldsurge
    mogreps_cs_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/mogreps/coldsurge
    mogreps_cs_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_CS_data/mogreps/plot_ens_new

  bsiso:
    mogreps_bsiso_queryfile: /home/users/prince.xavier/MJO/Monitoring_new/BSISO/mogreps/mjo_combined.query
    mogreps_bsiso_raw_dir: /scratch/hadpx/SEA_monitoring/raw_data/mogreps/MJO
    mogreps_bsiso_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/mogreps/MJO
    mogreps_bsiso_archive_dir: /project/MJO_GCSS/SEA_monitoring/processed_BSISO_data/mogreps/bsiso_new/
    mogreps_bsiso_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_BSISO_data/mogreps/plot_ens_new

glosea:
  glosea_dummy_queryfiles_dir: /scratch/hadpx/SEA_monitoring/temp

  mjo:
    # My new folder to replace this. Now I use my own tool to download and process data
    glosea_mjo_queryfile: /home/users/prince.xavier/MJO/Monitoring_new/MJO/glosea/mjo_combined.query
    glosea_mjo_raw_dir: /scratch/hadpx/SEA_monitoring/raw_data/glosea/MJO
    glosea_mjo_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/glosea/MJO
    glosea_mjo_archive_dir: /project/MJO_GCSS/SEA_monitoring/processed_MJO_data/glosea/rmms/
    glosea_mjo_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_MJO_data/glosea/plot_ens_new

  cs:
    # My new folder to replace this. Now I use my own tool to download and process data
    glosea_cs_queryfile: /home/users/prince.xavier/MJO/Monitoring_new/COLDSURGE/glosea/cs_combined.query
    glosea_cs_raw_dir: /scratch/hadpx/SEA_monitoring/raw_data/glosea/coldsurge
    glosea_cs_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/glosea/coldsurge
    glosea_cs_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_CS_data/glosea/plot_ens_new

  bsiso:
    glosea_bsiso_raw_dir: /scratch/hadpx/SEA_monitoring/raw_data/glosea
    glosea_bsiso_processed_dir: /scratch/hadpx/SEA_monitoring/processed_SEA_data/glosea/MJO
    glosea_bsiso_archive_dir: /project/MJO_GCSS/SEA_monitoring/processed_BSISO_data/glosea/bsiso_new/
    glosea_bsiso_plot_ens: /project/MJO_GCSS/SEA_monitoring/processed_BSISO_data/glosea/plot_ens_new
